---
- hosts: localhost # server we are running this againts
  connection: local # since we are running this directly on the server
  become: true # to enable sudo

  tasks:
    - name: Install packages
      package:
        name:
          - atop
          - mc
          - tmux
          - tree
