- name: Install Cron Job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/fanpero87/ansible-test.git > /dev/null"
# the "-o" parameter indicates that this should run when there is an update to the Github repo
# if there is no change, then it wont run
